"""initial schema

Revision ID: bb48b53baff5
Revises:
Create Date: 2026-06-09 16:30:10.389499

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bb48b53baff5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_table('novels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('original_title', sa.String(length=512), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('source_site', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('cover_storage_key', sa.String(length=512), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_novels'))
    )
    op.create_index(op.f('ix_novels_slug'), 'novels', ['slug'], unique=True)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('auth_provider', sa.String(length=64), nullable=True),
    sa.Column('auth_provider_subject', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_storage_key', sa.String(length=512), nullable=True),
    sa.Column('translated_storage_key', sa.String(length=512), nullable=True),
    sa.Column('raw_status', sa.String(length=64), nullable=False),
    sa.Column('translation_status', sa.String(length=64), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], name=op.f('fk_chapters_novel_id_novels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters'))
    )
    op.create_index(op.f('ix_chapters_novel_id'), 'chapters', ['novel_id'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], name=op.f('fk_crawl_jobs_novel_id_novels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_jobs'))
    )
    op.create_index(op.f('ix_crawl_jobs_novel_id'), 'crawl_jobs', ['novel_id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    op.create_table('library_items',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], name=op.f('fk_library_items_novel_id_novels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_library_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'novel_id', name=op.f('pk_library_items'))
    )
    op.create_table('novel_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=64), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], name=op.f('fk_novel_requests_novel_id_novels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_novel_requests_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_novel_requests'))
    )
    op.create_index(op.f('ix_novel_requests_status'), 'novel_requests', ['status'], unique=False)
    op.create_index(op.f('ix_novel_requests_user_id'), 'novel_requests', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], name=op.f('fk_reviews_novel_id_novels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_index(op.f('ix_reviews_novel_id'), 'reviews', ['novel_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('reading_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_reading_history_chapter_id_chapters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], name=op.f('fk_reading_history_novel_id_novels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reading_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_history'))
    )
    op.create_index(op.f('ix_reading_history_novel_id'), 'reading_history', ['novel_id'], unique=False)
    op.create_index(op.f('ix_reading_history_user_id'), 'reading_history', ['user_id'], unique=False)
    op.create_table('reading_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_reading_progress_chapter_id_chapters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], name=op.f('fk_reading_progress_novel_id_novels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reading_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'novel_id', name=op.f('pk_reading_progress'))
    )
    op.create_table('translation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('provider_key', sa.String(length=128), nullable=True),
    sa.Column('provider_model', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('token_input', sa.Integer(), nullable=True),
    sa.Column('token_output', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_translation_jobs_chapter_id_chapters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], name=op.f('fk_translation_jobs_novel_id_novels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_translation_jobs'))
    )
    op.create_index(op.f('ix_translation_jobs_chapter_id'), 'translation_jobs', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_translation_jobs_novel_id'), 'translation_jobs', ['novel_id'], unique=False)
    op.create_index(op.f('ix_translation_jobs_status'), 'translation_jobs', ['status'], unique=False)
    op.create_table('provider_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('provider_key', sa.String(length=128), nullable=True),
    sa.Column('provider_model', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['translation_jobs.id'], name=op.f('fk_provider_requests_job_id_translation_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_requests'))
    )
    op.create_index(op.f('ix_provider_requests_job_id'), 'provider_requests', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_requests_job_id'), table_name='provider_requests')
    op.drop_table('provider_requests')
    op.drop_index(op.f('ix_translation_jobs_status'), table_name='translation_jobs')
    op.drop_index(op.f('ix_translation_jobs_novel_id'), table_name='translation_jobs')
    op.drop_index(op.f('ix_translation_jobs_chapter_id'), table_name='translation_jobs')
    op.drop_table('translation_jobs')
    op.drop_table('reading_progress')
    op.drop_index(op.f('ix_reading_history_user_id'), table_name='reading_history')
    op.drop_index(op.f('ix_reading_history_novel_id'), table_name='reading_history')
    op.drop_table('reading_history')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_novel_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_novel_requests_user_id'), table_name='novel_requests')
    op.drop_index(op.f('ix_novel_requests_status'), table_name='novel_requests')
    op.drop_table('novel_requests')
    op.drop_table('library_items')
    op.drop_index(op.f('ix_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_novel_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_chapters_novel_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_novels_slug'), table_name='novels')
    op.drop_table('novels')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
