"""Core abstractions and shared types for Novel AI."""

from novelai.core.chapter_state import ChapterMetadata, ChapterState, ChapterStateTransition
from novelai.core.errors import (
    ConfigError,
    ExportError,
    NovelAIError,
    PipelineError,
    PipelineStageError,
    ProviderAPIError,
    ProviderConfigError,
    ProviderError,
    ProviderErrorCode,
    SourceConfigError,
    SourceError,
    SourceFetchError,
    StorageError,
)
from novelai.core.platform import (
    ChapterVersion,
    ChapterVersionKind,
    CrawlJob,
    CrawlJobKind,
    EditHistoryEntry,
    JobStatus,
    NovelRequestStatus,
    PlatformReviewStatus,
    TranslationJob,
    TranslationJobKind,
)

__all__ = [
    "ChapterMetadata",
    "ChapterState",
    "ChapterStateTransition",
    "ChapterVersion",
    "ChapterVersionKind",
    "ConfigError",
    "CrawlJob",
    "CrawlJobKind",
    "EditHistoryEntry",
    "ExportError",
    "JobStatus",
    "NovelAIError",
    "NovelRequestStatus",
    "PipelineError",
    "PipelineStageError",
    "PlatformReviewStatus",
    "ProviderAPIError",
    "ProviderConfigError",
    "ProviderError",
    "ProviderErrorCode",
    "SourceConfigError",
    "SourceError",
    "SourceFetchError",
    "StorageError",
    "TranslationJob",
    "TranslationJobKind",
]
